### ISSUE TITLE
Redispatch within the same chain is not being authorized

### ISSUE THREAD

**Issue by nicholeous** [interbit/interbit#108]
When redispatching a `@@interbit/START_PROVIDE_STATE` or `@@interbit/START_CONSUME_STATE` from within the chain's covenant an `unauthorized` message is received.

This appears to be caused by an authorization check that uses the private key or chain id from a signed action with the ACL. However, redispatched actions do not have public keys, chain ids or signatures, and the ACL check fails. This problem can be worked around in the covenant by adding the public key from the original action.

**Comment by pekeler** [comment]
Fixed in 0.6.0
