### ISSUE TITLE
Docs are impossible to find from main site

### ISSUE THREAD

**Issue by furiousOyster** [interbit/interbit#120]
I came to interbit.io and looked for docs.  There are none.  But I know we have some, because I copied them over.

**Comment by karikushi** [comment]
@furiousOyster Issue #11 addresses this. We've added a link to the docs in the footer nav, at the top of the dev overview page, and as the first item on the dev resources page.

**Comment by Rauchs** [comment]
They'll also be linked to within the Developer content once they're ready
