### ISSUE TITLE
Template - Improve User Experience for Action Types

### ISSUE THREAD

**Issue by jared-dykstra** [interbit/interbit#136]
Because `actionTypes` is [defined as an object](https://github.com/interbit/interbit/blob/master/packages/template/src/interbit/private/actions.js#L3-L6), there is no error detection for a typo.  For example, using `actionTypes.MEEMO` would not result in an error--either by the linter or at runtime.

Two possible improvements:
1. Create a separate `actionTypes.js` which exports just action type constants.
2. Proxy the ActionTypes object for run-time detection, either in the existing file or in a new file

A decision needs to be made regarding which change, if any, if preferred.  I can submit a PR.

**Comment by jared-dykstra** [comment]
Example of how a proxy helps:
```js
const covenantName = 'template-private'

const actionTypes = new Proxy(
  {
    MEMO: `${covenantName}/MEMO`,
    ADD: `${covenantName}/ADD`
  },
  {
    get: (obj, prop) => {
      if (prop in obj) {
        return obj[prop]
      }
      throw new Error(`Invalid action type ${prop}`)
    }
  }
)

const actionCreators = {
  memo: text => ({
    type: actionTypes.MEMO,
    payload: { text }
  }),

  add: number => ({
    type: actionTypes.ADD,
    payload: { number }
  }),

  subtract: number => ({
    type: actionTypes.SUBTRACT,
    payload: { number: 0 - number }
  })
}

module.exports = {
  actionTypes,
  actionCreators
}
```

![image](https://user-images.githubusercontent.com/9967320/39712145-353d65b2-51df-11e8-8290-9a9c429f9699.png)

**Comment by jared-dykstra** [comment]
Alternatively, removing the actionType definitions to a separate file called `actionTypes.js` and using import in `actions.js` will result in the following compile error on the console, because 'SUBTRACT' wasn't defined in actionTypes.js

actionTypes.js
```js
const covenantName = 'template-private'
export const MEMO = `${covenantName}/MEMO`
export const ADD = `${covenantName}/ADD`
```
actions.js
```js
import * as actionTypes from './actionTypes'

const actionCreators = {
  memo: text => ({
    type: actionTypes.MEMO,
    payload: { text }
  }),

  add: number => ({
    type: actionTypes.ADD,
    payload: { number }
  }),

  subtract: number => ({
    type: actionTypes.SUBTRACT,
    payload: { number: 0 - number }
  })
}

module.exports = {
  actionTypes,
  actionCreators
}
```


```
Compiling...
Failed to compile.
./src/interbit/private/actions.js
20:12-32 "export 'SUBTRACT' (imported as 'actionTypes') was not found in './actionTypes'
```

**Comment by djlmills** [comment]
@jared-dykstra 
We have avoided import/export in covenant code because of deployment issues, but for me, that is a compelling reason for sorting this out. The Proxy suggestion is worth adopting in the interim.

**Comment by jared-dykstra** [comment]
The proxy works well.  I recommend it.   It makes the code more robust, but there is then the added complexity of the proxy itself.  I think the extra complexity can be mitigated with a simple comment:

```js
const covenantName = 'template-private'

const actionTypes = {
  MEMO: `${covenantName}/MEMO`,
  ADD: `${covenantName}/ADD`
}

// Export a proxy so an exception is thrown in case an undefined property is accessed
module.exports = new Proxy(actionTypes, {
  get: (obj, prop) => {
    if (prop in obj) {
      return obj[prop]
    }
    throw new Error(
      `Invalid action type "${prop}" in covenant "${covenantName}"`
    )
  }
})
```
