### ISSUE TITLE
IO / Interbit for Biz (Copy edit)

### ISSUE THREAD

**Issue by Rauchs** [interbit/interbit#140]
"Privacy and scalability

Joining blockchains means applications are easier to integrate and can be designed with purpose-built chains that perform specific tasks at scale."

Can this be re-written without jargon? The intended audience isn't technical, and the sentence above doesn't seem like it follows the heading topic.

**Comment by JDMilroy** [comment]
Privacy and Scalability
Chain joining is unique to Interbit. Chain joining delivers privacy by separating chains and scale by joining them.

**Comment by Rauchs** [comment]
Sounds great. Clarified the second point about scale.

Privacy and Scalability
Chain joining is unique to Interbit. Chain joining delivers privacy by separating chains and delivers scale by joining them.
