### ISSUE TITLE
Block as fast as possible and only as much as possible

### ISSUE THREAD

**Issue by djlmills** [interbit/interbit#168]
Currently blocking happens every 2 seconds no matter what.

Ideally it would happen as soon as a new action arrives.  This is useful because some operations, such as cAuth, require block formation from 3 chains or so, which has a combined latency of as much as 10 seconds in some case.  If it was AFAP, then that would be near instant.

Also it should be configurable to only block when a new action arrives - basically a configurable strobe time, which may be indefinite.  This is useful for when we do not want many blocks, such as a user chain that is only active while they are logged in.

**Comment by pekeler** [comment]
Wouldn't what you're proposing result in a new block for every action?

Strobing by itself should not make the chain longer. If it does, this might be a bug.

**Comment by djlmills** [comment]
Yes, you are correct. This would result in a block for every action, so it is most appropriate for chains that inherently have low throughput but where latency is a real issue, such as an individuals private chain which needs to be responsive.

I guess this means the strobing rate would need to be configurable with a finer granularity, either for specific chains or specific covenants.

Strobing by itself doesn't normally make the chain chain longer (you can see that in the block explorer). However, I have seen this behaviour with child chains, where a new block was added each time the parent strobed. I believe this problem was fixed.

**Comment by furiousOyster** [comment]
Strobing doesn't make the chain longer, but it sends each strobe block every time.  This is a problem if the block state is large as it can drown the poor little browser which doesn't have much mobile data on its 2G roaming plan in a foreign country....

**Comment by pekeler** [comment]
> this means the strobing rate would need to be configurable with a finer granularity, either for specific chains or specific covenants

I'd prefer a dynamic behaviour so we automatically get low latency for a low rate of actions, and as the number of actions per second increases, the chain automatically increases its latency (i.e. blocks less often).


> Strobing doesn't make the chain longer, but it sends each strobe block every time.

How about if a block doesn't include a new state, it just includes a pointer to (hash-value of)) the last block that did have the state? ... Or maybe this is not worth the effort since we already know that we'll implement state-diffing soon.



Let's break these into separate issues.

**Comment by brentbenton** [comment]
Migrated to new Core coordination process.
