### ISSUE TITLE
Instead of timeout when peer does not connect use an exponential backoff

### ISSUE THREAD

**Issue by nicholeous** [interbit/interbit#179]
Currently when a node cannot connect to a peer the waitForState will timeout because it cannot get state for the expected chain. It would be better if the error was not produced for a failed connect and instead the node attempted to connect again at longer and longer (exponential) intervals up to a set interval of ???

Sometimes a peer is down for a valid reason, such as a redeployment or an outage.

**Comment by brentbenton** [comment]
Migrated to new Core coordination process.
