### ISSUE TITLE
Copy updates > Developers

### ISSUE THREAD

**Issue by Rauchs** [interbit/interbit#226]
Apps built with Interbit are:

Fault tolerant
Resist faults, malicious and benign

Auditable
Perfect audit, no logs

Disaster recoverable
RTO & RPO nearly zero

Ensured data integrity
Immutable app history

Distributed
Choose between global or local deployments

Highly available
Always on, cross cloud applications

Redundant
No external backups

**Comment by karikushi** [comment]
@Rauchs The original "High availability" is better than "Highly available". See https://en.wikipedia.org/wiki/High_availability, it's an industry specific term so we should probably stick with it.

**Comment by Rauchs** [comment]
Gotcha, thanks for the clarification.

I'll update the heading to accommodate.

------

**How are they better?**

Fault tolerant
Resist faults, malicious and benign

Auditable
Perfect audit, no logs

Disaster recoverable
RTO & RPO nearly zero

Ensured data integrity
Immutable app history

Distributed
Choose between global or local deployments

High availability
Always on, cross cloud applications

Redundant
No external backups
