### ISSUE TITLE
Core: Add support for an optional 'public' role to configure actions accessible to any users

### ISSUE THREAD

**Issue by djlmills** [interbit/interbit#227]
Rationale:

1. Learning: The PPC pattern embedded in the interbit `template` is complex and causes major roadblocks for developers coming to Interbit for the first time. This means we can put together single chain samples and provide a better progression through the learning process and build up to the PPC pattern gradually.

2. Multi-user applications: Having a public chain that all users can dispatch specific actions to makes possible all sorts of multi-user applications.

The kind of thing I had in mind is:

```js
case '@@interbit/DEPLOY': {
     // Permit all users to dispatch ADD actions to the public chain
     const addToAclAction = addToAcl({
       actionPermissions: { [actionTypes.ADD]: ['public'] },
       roles: { public: ['*'] }
     })

     console.log('REDISPATCH: ', addToAclAction)
     return redispatch(state, addToAclAction)
   }
```

**Comment by pekeler** [comment]
`*` is now allowed as a value for roles as of release 0.9.0.
