### ISSUE TITLE
Improving MTTF

### ISSUE THREAD

**Issue by btltyler** [interbit/interbit#233]
We don't presently measure MTTF.  We need to and improve it.

### Improving MTTF Steps for Success
1.  Automate using the platform
- Build a tool to step through the accounts lifecycle repeatedly
- Tool needs to run from a browser experience (EG: Headless Chrome) and be able to target local and deployed environments
- Tom loves Browserstack

2. Bring over action logging from Hosting repo to upload all the logs to Cloudfront (and elsewhere)

3. Run platform automation and break things
- run in debug
- find out what MTTF is
- get a reliable failure and ship it to the Core team

4. Take fixes and re-run

### Later
1.  Setup random user operations tests

**Comment by brentbenton** [comment]
Suggestion from Mr. Mills on initial goals: 50 user chains.

Uptime of 24 hours.

Please discuss.

**Comment by btltyler** [comment]
Finished with report generated and recommendations/solutions for identified problems.
