### ISSUE TITLE
Get version from interbit 

### ISSUE THREAD

**Issue by nicholeous** [interbit/interbit#28]
Interbit export should have a version() function that returns the semver of the current versions.

**Comment by brentbenton** [comment]
No, pull that out of the package.json

**Comment by pekeler** [comment]
I've wanted this feature myself in the past.
It's easier&cleaner for core to pull it out of its package.json and expose it than for a consumer of core.

**Comment by nicholeous** [comment]
@brentbenton When interbit loads on the browser from the middleware we do not have access to package.json so we need to get the version from interbit core itself

**Comment by brentbenton** [comment]
It appears we're on the same page.

That was Tom on my PC above, btw.

**Comment by pekeler** [comment]
added `VERSION` to top-level export in 0.8.0

```
const {VERSION} = require('interbit-covenant-utils')
// or
const {VERSION} = require('interbit-core')
```
