### ISSUE TITLE
Kill chain feature request

### ISSUE THREAD

**Issue by nicholeous** [interbit/interbit#31]
Hosting generates a significant number of short useful duration chains (minutes max). Afterwards they have no utility and should be destroyed by either the chain itself or a parent chain. Destruction is preferably by the parent chain.

Additionally, we want to kill Private User Data chains at a User's request. Tom knows the details required here as this may additionally need Cascade Delete of relevant user data that has propagated into other Chains.

**Comment by JDMilroy** [comment]
Is this going to be ready for the Consensus hackathon, later this week!?  (Our challenge topic for the hackathon is based this ability.)  What are our options if its not ready?

**Comment by pekeler** [comment]
This has been added to v0.7.0. Without cascade delete (which we consider pointless from a security perspective). I'm closing this and suggest we create a new issue if you need us to support cascade deletes.
