### ISSUE TITLE
OpenPGP Exception kills chain blocking

### ISSUE THREAD

**Issue by btltyler** [interbit/interbit#485]
I believe the browser was using a bad key in this instance but am not certain.

Backend Master Node printed after a localhost browser connect:
2018-06-09T18:37:22.123403+00:00 app[web.1]: platform-deploy:  Error: Error encrypting message: No keys, passwords, or session key provided.

After this my stats slice stopped printing which would only happen if blocking stopped.  Had to restart the backend and clear browser memory to resolve this.

It's likely we need to rescue from an OpenPGP error somewhere but I'll need to sync with the team on Monday to find out where (The stack trace was useless unfortunately).

**Comment by jared-dykstra** [comment]
Yes, that's correct.  Interbit core changed to unarmored keys, but used the same localstorage path.  They didn't provide backwards compatibility. All keys beed to be regenerated, either manually or by clearing localstorage

**Comment by btltyler** [comment]
Thanks, confirmed then.

One problem with this is an attacker could kill your interbit environment just by providing a bad key.  I assume this will fail the security audit.

**Comment by brentbenton** [comment]
Migrated to new Core coordination process.
