### ISSUE TITLE
Put in a watcher for component updates

### ISSUE THREAD

**Issue by karikushi** [interbit/interbit#49]
Currently, we need to rebuild every time components in lib-react-interbit are updated in order to see the changes. nwb does not have a watcher, unfortunately, so we may want to move to something else.

**Comment by nicholeous** [comment]
NWB Does not support a watch command for various reasons. Because of this and the way that it does not play nicely with heroku we will be rolling our own build step the works similarly to the rest of our libraries but does not create a UMD build (which we have not actually used).
