### ISSUE TITLE
Regenerate browser keys if unknown

### ISSUE THREAD

**Issue by jared-dykstra** [interbit/interbit#495]
## Original issue description
If a browser has keys in localstore from a previous access to an interbit-powered site, it will attempt to use those keys when loading the page.  If the server-node was stopped and restarted, the server will not know about the keys.  In this scenario, there is no error message.  The site doesn't work, but will if the user clears localstore and reloads.

The big picture:  If a server node is stopped and restarted, the end-to-end system should still work and never get into an invalid/stuck state.

## Actual issue
The problem is not with the local browser keys, but with the existing private chain in local storage. This chain is effectively orphaned  as the server node does not know about it and cannot host it. In this case, the local chain must be discarded, a new chain created using the chain sponsorship process. Creating a new chain will cause data loss unless the current chain state can be applied to the newly created chain.

**Comment by btltyler** [comment]
Redux Saga was actually throwing errors and blocking stopped when I tested this.  It was unrecoverable.
