### ISSUE TITLE
Interbit cannot find manifest file?

### ISSUE THREAD

**Issue by jared-dykstra** [interbit/interbit#692]
When I run `interbit:start` in the template project, it seems to be unable to locate the manifest.  How do I correct that?

Running `npm run interbit:start`
```
Loading config at C:\github\helixapps\interbit\packages\interbit-template/interbit.config.js
Manifest file does not exist at location C:\github\helixapps\interbit\packages\interbit-template/dist//interbit.manifest.json
interbit start: --dbPath option will set $DB_PATH environment variable.
template-public { location:
   'C:\\github\\helixapps\\interbit\\packages\\interbit-template\\src\\interbit\\public' }
template-control { location:
   'C:\\github\\helixapps\\interbit\\packages\\interbit-template\\src\\interbit\\control' }
template-private { location:
   'C:\\github\\helixapps\\interbit\\packages\\interbit-template\\src\\interbit\\private' }
STARTING HYPERVISOR
```

Note the error: _Manifest file does not exist...interbit-template/dist//interbit.manifest.json_

The [documentation](https://docs.interbit.io/reference/interbit-cli/build.html) says interbit supports a `--manifest` flag, I modified `scripts` in package.json and set it to this:
```js
"interbit:start": "interbit --manifest ./build/manifest.json start --db-path ./db-interbit --port 5000 --dev",
```

But that doesn't seem to work, and results in an error: 
```
jared@Jared-Y50 MINGW64 /c/github/helixapps/interbit/packages/interbit-template (master)
$ npm run interbit:start

> interbit-template@0.4.46 interbit:start C:\github\helixapps\interbit\packages\interbit-template
> interbit --manifest ./build/manifest.json start --db-path ./db-interbit --port 5000 --dev

node: bad option: --manifest
```

interbit doesn't seems to have a `--help` flag either.

...How do I set the location of the manifest file to the correct location?

**Comment by djlmills** [comment]
Looks like you need to pull the latest changes. #678 addressed both this issue and your previous one.

**Comment by nicholeous** [comment]
This is merely a warning and not a problem. Start does not require a manifest. 

There is a documentation update coming that will mark that option as optional. The warning will remain.

All options must be provided after the command. To provide a manifest, move the `--manifest` option after the `start` command.
