### ISSUE TITLE
Template project should have 'eslint-plugin-jest' installed as dev dependency

### ISSUE THREAD

**Issue by jared-dykstra** [interbit/interbit#707]
`interbit-template/.eslintrc` references the `jest` plugin, but it's not specified in `package.json`

In the template project, eslint errors out with: 
`Failed to load plugin jest: Cannot find module 'eslint-plugin-jest'`

Please either add a dev dependency to package.json or remove the plugin from .eslintrc

Note: This is an issue if run separately--outside of it's normal location (without Lerna)

**Comment by nicholeous** [comment]
@jared-dykstra I can't find an `.eslintrc` file in the path you specified at `packages/interbit-template/.eslintrc`.

However, there is an `.eslintrc` file in `packages/interbit-template/src/interbit/.eslintrc`.

This file should not be there and we will remove it. We are using [CRA](https://github.com/facebook/create-react-app) to generate the template with the hope that we don't need to maintain any linter settings outside of our root repository. (One linter to rule them all)

If you wish to lint your project differently than the CRA default settings, after you've copied the template feel free to add custom linter settings and the dependencies to support that the same way you would extend another CRA booted app.

**Comment by jared-dykstra** [comment]
Sorry, the original location of `.eslintrc` was not within the `interbit-template` package, but was here: https://github.com/interbit/interbit/blob/master/.eslintrc 

For consistency, I want to use the same ruleset that you're using.

All I'm trying to do is create a forkable repo as the basis for new apps.  That way all my new apps can easily receive changes that your team makes by merging from the upstream fork.  That repo is here: https://github.com/helixapps/interbit-template.
